- name: demo on play level variables
  hosts: localhost
  vars:
    NAME: "Sai"
    ROLE: "AWS DEvOps Engineer"
    LOCATION: "UK"
  tasks:
  - name: printing the information
    debug :
      msg: "{{NAME} is working as a {{ROLE}} in {{LOCATION}}}"
  

