- name: print even or odd number
  hosts: localhost
  connection: local
  vars_prompt:
  - name: num
    prompt: "plese enter the number to validate even or odd"
    private: false
  tasks: 
  - name: validate even or not and print if it's even
    when: num | int % 2 == 0 #type casting to int, by default it's reads as a string
    debug:
      msg: "The Given number: {{num}} is even number"

  - name: validate odd number or not and print if it's odd
    when: num | int % 2 != 0
    debug:
      msg: "The Given number: {{num}} is odd number"

