- name: age verification
  hosts: localhost
  connection: local
  vars_prompt:
  - name: age
    prompt: "plesae enetr your age"
    private: false
  tasks:
  - name: validate age and print
    when: age | int > 18
    debug:
      msg: "Your age {{age}} is above 18, so allowed to vote"
  
  - name: validate age and print
    when: age | int < 18
    debug:
      msg: "Your age {{age}} is under 18, not allowed to vote"