- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: print installing packages
    package:
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql-server
    - nodejs