- name: check the service status if stopped then run
  hosts: frontend
  become: yes
  tasks:
  - name: check service status and if stopped then start
  loop:
  - { name: "nginx", state: "stopped" }
  - { name: "mysqld", state: "stopped" }
  when: "{{item.state}}" == "stopped"
  systemd_service:
   name: "{{item.name}}"
   state: started
   