- name: fetching the service status from ansible facts and if stopped then start
  hosts: frontend
  become: yes
  tasks:
  - name: gather service facts
    service_facts:
  
  - name: print all services facts
    debug:
      var: ansible_facts.services
  
  - name: start service if stopped
    loop:
    - nginx
    - mysqld
    when: ansible_facts.services[item+".service"].state == "stopped"
    systemd_service:
       name: "{{item}}"
       state: started
    
