- name: demo on shell vs command
  hosts: localhost
  connection: local
  tasks:
  - name: list the files
    command: ls -l 
    register: files_list

  - name: print files list
    debug:
      msg: "Files List: {{files_list.stdout}}"

  - name: find the root user from passwd files
    shell: cat /etc/passwd | grep root
    register: root_user_details

  - name: print root user details
    debug:
      msg: "{{root_user_details.stdout}}"

  - name: append logs to log files
    shell: sudo dnf install nginx -y &>> /dev/null

  - name: get nginx version  
    command: nginx -v
    register: nginx_version


  - name: verifying nginx Version
    debug:
      msg: "Nginx Version: {{nginx_version.stderr}}"

